# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b75ddbd11d28c2839cda640e5286929ee2f23d6ad55dcb9ed9389245d960c9f2d821e37d508d0482cee00dd8f86838893e78b68462ce84a538c990507dd6f5f8

test:
  secret_key_base: da77ed3e3bd1e7b6821c28b4023b7e89c40b7157bf49efaf5b35ebcb94bc5a49c4e88f38bc2516a996698d69b99a9cca5e1df1d8ef63ccbca3909a0def5aaffe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
